export * from "@seeders/configGroupsSeeder";
export * from "@seeders/fuelTypesSeeder";
export * from "@seeders/groupsSeeder";
export * from "@seeders/maintenanceTypesSeeder";
export * from "@seeders/suppliersSeeder";
export * from "@seeders/unitTypesSeeder";
export * from "@seeders/unitsSeeder";
export * from "@seeders/unitMeasurementsSeeder";
export * from "@seeders/setPointSeeder";