export const USERS_SERVICE = 'USERS_SERVICE';
export const TRAVEL_PLANNING_SERVICE = 'TRAVEL_PLANNING_SERVICE';
export const UNITS_SERVICE = 'UNITS_SERVICE';
export const EVENTS_SERVICE = 'EVENTS_SERVICE';
export const TWILIO_SERVICE = 'TWILIO_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';
export const DRIVERS_SERVICE = 'DRIVERS_SERVICE';
export const NATS_SERVICE = 'NATS_SERVICE';